### ISSUE TITLE
Question: using array of values in frontmatter

### ISSUE THREAD

**Issue by ppipada** [docsify-mustache/docsify-mustache.github.io#7]
I am trying to use an array of values from frontmatter using this plugin. Is there a way I can get the value one at a time?

E.g: 
```
---
tags: [t1, t2, t3]
---
```

When I access that in md file as `{{tags}}` it comes as `t1,t2,t3`.
Is there a way I can access each individual value and do something with it? E.g: associate a url with each value.

**Comment by szkiba** [comment]
Sure, you can access elements by index: `{{tags.0}}` or `{{tags.1}}` etc..
Or you can iterate over array:
```
{{#tags}}

Hey, {{.}}

{{/tags}}
```

**Comment by ppipada** [comment]
Thanks a lot. This helps !!

Suggestions:
- I could not find this info in the docs. Can we add this please? 

Observation:
- If the array list [tags in above ex] has a string that has '-' in it, the mustache rendering breaks using `{{.}}` syntax. What is needed is add the string in single quotes ('').
E.g: if the frontmatter is 
```
tags: [t1, t-2, t3]
```
rendering for t-2 breaks. 
Solution is to do:
```
tags: [t1, 't-2', t3]
```

I could add a pull request if you could please guide me on where to add this in docs.

**Comment by szkiba** [comment]
This is not in docs, because it is mustache usage information, not related directly to plugin functionality...
Maybe you should create a blog post about your founding...

**Comment by ppipada** [comment]
Got it. Thanks.

Reference blog post: 
https://ppipada.github.io/post/markdown/2020-04-29-docsify-mustache/
